name: cached_network_image
description: Flutter library to load and cache network images.
  Can also be used with placeholder and error widgets.
homepage: https://github.com/Baseflow/flutter_cached_network_image
version: 3.2.0

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  octo_image: ^1.0.0
  flutter_image_compress: ^1.1.0
  cached_network_image_platform_interface:
    git:
      url: https://github.com/jja08111/flutter_cached_network_image.git
      path: cached_network_image_platform_interface
      ref: app/ai
  cached_network_image_web:
    git:
      url: https://github.com/jja08111/flutter_cached_network_image.git
      path: cached_network_image_web
      ref: app/ai


dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.1
  flutter_lints: ^1.0.4
  file: ^6.1.0

environment:
  flutter: ">=1.24.0-10.2.pre"
  sdk: ">=2.12.0 <3.0.0"
